name = "DqdLeadsCavity"
uuid = "9c663722-20cf-451c-a5d1-0d21e07208d9"
version = "1.0.0-DEV"
authors = ["ntorresd <ntorresd@unal.edu.co> and contributors"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
QuantumToolbox = "6c2fb7c5-b903-41d2-bc5e-5a7c320b9fab"

[compat]
LinearAlgebra = "1.12.0"
QuadGK = "2.11.2"
QuantumToolbox = "0.37.0"
julia = "1.12.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
