name = "DqdLeadsCavity"
uuid = "9c663722-20cf-451c-a5d1-0d21e07208d9"
version = "1.0.0-DEV"
authors = ["ntorresd <ntorresd@unal.edu.co> and contributors"]

[deps]
QuantumToolbox = "6c2fb7c5-b903-41d2-bc5e-5a7c320b9fab"

[compat]
QuantumToolbox = "0.37.0"
julia = "1.12.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
