name = "DqdLeadsCavity"
uuid = "9c663722-20cf-451c-a5d1-0d21e07208d9"
authors = ["ntorresd <ntorresd@unal.edu.co> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.12.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
